include:
  - board: seeeduino_xiao_ble   # ボード名（Seeeduino XIAO BLE）
    shield: sparkle_left          # 左側シールド（totem_left）を含める
  - board: seeeduino_xiao_ble
    shield: sparkle_right         # 右側シールド（totem_right）を含める
  - board: seeeduino_xiao_ble
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
# XIAOには settings_reset（リセット用のビヘイビア）はない（必要なものは無い）
