file_format: "1"  # 設定ファイルのフォーマットバージョン。ZMK では通常 "1"
id: sparkle          # このシールドの識別子（ZMK内部で使われる）
name: SPARKLE        # シールドの表示名（ユーザー向け）
type: shield       # このファイルはシールド定義
url: https://github.com/Hinata-344/Sparkle# リポジトリURL（任意）

requires: [seeeduino_xiao_ble]  # このシールドが依存するボード。ここではXIAO BLE

features:
  - keys  # キー入力を持つシールドであることを明示

siblings:
  - sparkle_left     # 分割キーボードの左側シールドとして認識される
  - sparkle_right    # 分割キーボードの右側シールドとして認識される
  - settings_reset
