manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware  # リモートリポジトリのベースURL

  projects:
    - name: zmk                              # プロジェクト名
      remote: zmkfirmware                    # 使用するリモート名（上記のzmkfirmware）
      revision: main                        # ブランチやコミットを指定（ここではmainブランチ）
      import: app/west.yml                  # サブマニフェストをインポートしてさらに管理

  self:
    path: config                           # このmanifestの自身のルートパス（configディレクトリ）
